FROM nginx
MAINTAINER jeecgos@163.com
VOLUME /tmp
VOLUME ["/app"]
ENV LANG zh_CN.UTF-8
RUN echo "server {  \
                      listen       2340; \
                      location   /{ \
                      proxy_redirect          off; \
                      proxy_set_header        Host Game; \
                      proxy_set_header        X-Real-IP \$remote_addr; \
                      proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for; \
                      root /app; \
                      index  index index.html; \
                  } \
                  access_log  /var/log/nginx/access.log ; \
              } " > /etc/nginx/conf.d/default.conf \
    &&  mkdir  -p  /var/www \
    &&  mkdir -p /var/www/html
EXPOSE 8089
